# Question 1

In [4]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [12]:
import numpy as np
lst1 = []
for i in range(0, 5):
    ele = int(input())
    
    lst1.append(ele)

a1 = np.array(lst1)
print("Array 1 is : ",a1)

lst2 = []
for i in range(0, 5):
    ele = int(input())
    
    lst2.append(ele)

a2 = np.array(lst2)
print("Array 2 is : ",a2)

arr = np.concatenate((a1,a2))
print("After concatenate : ",arr)

arr.sort()
print("After sorting",arr)

1
8
9
6
7
Array 1 is :  [1 8 9 6 7]
3
2
5
4
10
Array 2 is :  [ 3  2  5  4 10]
After concatenate :  [ 1  8  9  6  7  3  2  5  4 10]
After sorting [ 1  2  3  4  5  6  7  8  9 10]


# Question 3

In [16]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print("No. of dimention is : ",arr.ndim)
print("Size of array is : ",arr.size)

No. of dimention is :  2
Size of array is :  6


# Question 4 

In [60]:
#using np.newaxis methode

import numpy as np

arr = np.arange(1,13)
print("1-D array is : ",arr)

new = arr[np.newaxis, :]
arr2 = new.reshape(4,3)
print("2-D array is : ")
print(a)

1-D array is :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
2-D array is : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [66]:
#using expand_dim methode

x = np.arange(1,13)
print("1-D array is : ",x)

y = np.expand_dims(x, axis = 0)
a=y.reshape(4,3)
print("2-D array is : ")
print(a)

1-D array is :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
2-D array is : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Question 5

In [70]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Horizontal Append : ",np.hstack((a,b)))
print("Vertical Append : ")
print(np.vstack((a,b)))

Horizontal Append :  [1 2 3 4 5 6]
Vertical Append : 
[[1 2 3]
 [4 5 6]]


# Question 6

In [4]:
# USE set() AND len() TO COUNT UNIQUE VALUES IN A LIST

a_list = [1, 1, 2, 2, 3]
a_set = set(a_list)
number_of_unique_values = len(a_set)
print(number_of_unique_values)

3
